resolver: lts-4.1
packages:
- location:
    git: git://github.com/thsutton/edit-distance-vector.git
    commit: 52911ba84687951e5ff0b854183cd1846460b666
extra-deps: []
flags: {}
extra-package-dbs: []
